<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\FoodDelivery.Application\FoodDelivery.Application.csproj" />
		<ProjectReference Include="..\FoodDelivery.Domain\FoodDelivery.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="ClosedXML" />
		<PackageReference Include="Stripe.net" />
		<PackageReference Include="WebPush" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>